### ISSUE TITLE
Contibution

### ISSUE THREAD

**Issue by ArnolFokam** [fonkamloic/C_CPP_ADS#1]
make a project structure and i will be very pleased to contribute to your repo

**Comment by fonkamloic** [comment]
YOU are very welcome
My aim is to build some tool-sets in the most popular programming languages that can come in handy in any other personal or public project. It will also be a challenge to complete the problems found in [Hemant Jain's](https://www.amazon.com/Hemant-Jain/e/B06XDCB2KQ) books.

The main purpose of these project is to make the implementations generic and highly reusable so it should be very well documented.
